## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/api/*"
  to = "https://kick-a-ball.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200